/* Estimate the length of the string generated by a vprintf-like
   function.  Use by vasprintf and xvasprintf.
   Please review $(srcdir/SPL-README) for GNU licencing info. */

extern int libiberty_vprintf_buffer_size (const char *, va_list);
